classDiagram
    class burgerDelivery {
        +Number totalorders$
        +Number availableBurgers$
        +String meal
        +Number price
        +orderSlots()$
    }

class customers {
        +Number totalCustomers$
        +String customerEmail
        +String name
        +order()
        +orderComplete()
    }

    customers --> burgerDelivery : places